kind: Service
apiVersion: v1
metadata:
  name: player-database-postgres
  namespace: baseball
spec:
  selector:
    app: player-database-postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: player-database-postgres